# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
pt:
  languageCode: pt-br
  contentDir: content/pt
  title: BiomagLab USP RP
  params:
    description: O Laboratório de Biomagnetismo tem como objetivo estudar os campos magnéticos gerados pelos sistemas biológicos e a interação dos campos magnéticos externos com o corpo humano.
  menu:
    main:
      - name: Pesquisas
        url: 'researches'
        weight: 20
      - name: Softwares
        url: 'softwares'
        weight: 40
      - name: Membros
        url: 'people'
        weight: 30
      - name: Publicações
        url: 'publication'
        weight: 50
      - name: Contato
        url: 'contact'
        weight: 60
